{% set name = "PyFluxconserving" %}
{% set version = "0.0.14" %}
{% set url = "https://pypi.io/packages/source/" + name[0] + "/" + name + "/" + name + "-" + version + ".tar.gz" %}
# In case you wanna test locally
#{% set url = name ~ '-' ~ version ~ '.tar.gz' %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  fn: "{{ name }}-{{ version }}.tar.gz"
  url: "{{ url }}"
  sha256: 19e0bd4edce7dcd165de0161675c7cc8111dbb6b7c0228f191869d6b56fbc00a

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - matplotlib
    - numpy>=1.21.5
    - scipy
    - pip
    - python
  run:
    - matplotlib
    - numpy>=1.21.5
    - scipy
    - python

test:
  imports:
    - PyFluxconserving

about:
  home: "https://github.com/neutrinomuon/PyFluxconserving"
  license_file: 'LICENSE.txt'
  license_url: "https://github.com/neutrinomuon/PyFluxconserving/LICENSE.txt"
  summary: "Flux-conserving legacy routines in Fortran and Python"
  doc_url: "https://github.com/neutrinomuon/PyFluxconserving"
  dev_url: "https://github.com/neutrinomuon/PyFluxconserving"

extra:
  recipe-maintainers:
    - neutrinomuon
