{% set name = "pyfluxconserving" %}
{% set version = "0.0.9" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 2523d67df4ab8278ba2dacb422148f9eb039c27e16cfdd99ed03d8413761ae28

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - matplotlib
    - numpy
    - pip
    - python
  run:
    - matplotlib
    - numpy
    - python

test:
  imports:
    - pyfluxconserving

about:
  home: "https://github.com/neutrinomuon/pyfluxconserving"
  license_file: 'LICENSE.txt'
  license_url: "https://github.com/neutrinomuon/pyfluxconserving/LICENSE.txt"
  summary: "Flux-conserving legacy routines in Fortran and Python"
  doc_url: "https://github.com/neutrinomuon/pyfluxconserving"
  dev_url: "https://github.com/neutrinomuon/pyfluxconserving"

extra:
  recipe-maintainers:
    - neutrinomuon
