{% set name = "pyfluxconserving" %}
{% set version = "0.0.12" %}
{% set url = "https://pypi.io/packages/source/" + name[0] + "/" + name + "/" + name + "-" + version + ".tar.gz" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  fn: "{{ name }}-{{ version }}.tar.gz"
  url: "{{ url }}"
  sha256: 3b07df92351052c624339b1ce012c3d712f8fd5b2deca591b19664467985568f

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - matplotlib
    - numpy>=1.21.5
    - pip
    - python
  run:
    - matplotlib
    - numpy>=1.21.5
    - python

test:
  imports:
    - pyfluxconserving

about:
  home: "https://github.com/neutrinomuon/pyfluxconserving"
  license_file: 'LICENSE.txt'
  license_url: "https://github.com/neutrinomuon/pyfluxconserving/LICENSE.txt"
  summary: "Flux-conserving legacy routines in Fortran and Python"
  doc_url: "https://github.com/neutrinomuon/pyfluxconserving"
  dev_url: "https://github.com/neutrinomuon/pyfluxconserving"

extra:
  recipe-maintainers:
    - neutrinomuon
