name: Update README from pyfluxconserving

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get install jq -y
      
      #- name: Run update-readme script
      #  run: python scripts/update_readme.py

      - name: Update README with new version
        run: |
          TOKEN=${{ secrets.GITHUB_TOKEN }}
          FILE_PATH="README.md"
          BRANCH="main"
          COMMIT_MESSAGE="Update README with new version"
          
          # Get the current commit SHA
          COMMIT_SHA=$(curl -s -X GET \
            -H "Authorization: Bearer $TOKEN" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/neutrinomuon/pyfluxconserving/commits/$GITHUB_SHA" | jq -r '.sha')

          # Get the current commit SHA of the file
          CURRENT_COMMIT_SHA=$(curl -s -X GET \
            -H "Authorization: Bearer $TOKEN" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/neutrinomuon/pyfluxconserving/commits?path=$FILE_PATH" | jq -r '.[0].sha')
            
          # Print COMMIT_SHAs
          echo "COMMIT_SHA: $COMMIT_SHA"
          echo "CURRENT_COMMIT_SHA: $CURRENT_COMMIT_SHA"
          
          # Get the current file contents
          FILE_CONTENT=$(curl -s -X GET \
            -H "Authorization: Bearer $TOKEN" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/neutrinomuon/pyfluxconserving/contents/$FILE_PATH?ref=$BRANCH" | jq -r '.content')

          # Decode the file contents
          FILE_CONTENT=$(echo "$FILE_CONTENT" | base64 -d)

          # Update the file content with the new version
          NEW_VERSION=$(cat version.txt)
          UPDATED_CONTENT=$(echo "$FILE_CONTENT" | sed "s/last stable version: .*/last stable version: $NEW_VERSION/")

          # Encode the updated content
          # UPDATE_CONTENT_normal=$(echo -n "$UPDATED_CONTENT")
          # UPDATED_CONTENT=$(echo -n "$UPDATED_CONTENT" | base64)

          # Print debug information
          echo "TOKEN: $TOKEN"
          echo "COMMIT_SHA: $COMMIT_SHA"
          # echo "FILE_CONTENT: $FILE_CONTENT"
          # echo "UPDATED_CONTENT: $UPDATED_CONTENT"
          echo "NEW_VERSION: $NEW_VERSION"

           # Prepare the JSON data
          JSON_DATA=$(jq -n --arg message "$COMMIT_MESSAGE" --arg content "$UPDATED_CONTENT" --arg branch "$BRANCH" --arg sha "$COMMIT_SHA" \
            '{message: $message, content: $content, branch: $branch, sha: $sha}')

          # echo "JSON_DATA: $JSON_DATA"

          # Update the file on GitHub
          RESPONSE=$(curl -s -X PUT \
            -H "Authorization: Bearer $TOKEN" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -d "$JSON_DATA" \
            "https://api.github.com/repos/neutrinomuon/pyfluxconserving/contents/$FILE_PATH")

          echo "$RESPONSE"
